"""YAML 导出器。

将 Pydantic 数据模型序列化为 YAML 格式文件。
支持新的 yaml_schema.py 完整结构和旧的 script.py 兼容结构。
"""

import logging
from pathlib import Path
from enum import Enum

import yaml

from app.utils.file_utils import ensure_dir

logger = logging.getLogger(__name__)


# ============================================================
# 自定义 YAML Dumper
# ============================================================


class LRMDumper(yaml.SafeDumper):
    """LRM 脚本专用 YAML Dumper。

    支持：
    - 中文友好输出（Unicode 不转义）
    - 多行文本使用 | 块格式
    - Enum 值自动转为字符串
    - None 值不输出
    """


def _str_representer(dumper: yaml.Dumper, data: str) -> yaml.ScalarNode:
    """多行文本使用 | 块格式。"""
    if "\n" in data:
        return dumper.represent_scalar("tag:yaml.org,2002:str", data, style="|")
    return dumper.represent_scalar("tag:yaml.org,2002:str", data)


def _enum_representer(dumper: yaml.Dumper, data: Enum) -> yaml.ScalarNode:
    """Enum 值转为字符串。"""
    return dumper.represent_scalar("tag:yaml.org,2002:str", data.value)


def _none_representer(dumper: yaml.Dumper, data) -> yaml.ScalarNode:
    """None 值使用空字符串。"""
    return dumper.represent_scalar("tag:yaml.org,2002:null", "")


LRMDumper.add_representer(str, _str_representer)
LRMDumper.add_representer(Enum, _enum_representer)
LRMDumper.add_representer(type(None), _none_representer)


# ============================================================
# 导出函数
# ============================================================


def export_yaml(data, output_dir: Path, filename: str = "script.yaml") -> Path:
    """将数据导出为 YAML 文件。

    支持两种输入：
    1. Script 对象（from yaml_schema.py 或 script.py）
    2. dict（已转换好的字典）

    Args:
        data: 要导出的数据（Script 对象或 dict）。
        output_dir: 输出目录。
        filename: 输出文件名。

    Returns:
        输出文件路径。
    """
    ensure_dir(output_dir)
    output_path = output_dir / filename

    # 转换为字典
    if hasattr(data, "model_dump"):
        yaml_data = data.model_dump(mode="json", exclude_none=True, exclude_defaults=False)
    elif isinstance(data, dict):
        yaml_data = data
    else:
        raise TypeError(f"不支持的数据类型: {type(data)}")

    # 生成 YAML
    yaml_content = yaml.dump(
        yaml_data,
        Dumper=LRMDumper,
        allow_unicode=True,
        default_flow_style=False,
        sort_keys=False,
        width=120,
    )

    # 添加文件头注释
    header = (
        "# ============================================================\n"
        "# LRM Script - Generated by novel2script\n"
        "# Do not edit manually - regenerate from source novel\n"
        "# ============================================================\n\n"
    )

    output_path.write_text(header + yaml_content, encoding="utf-8")
    logger.info(f"YAML 已导出: {output_path}")

    return output_path


def export_from_script(script, output_dir: Path, filename: str = "script.yaml") -> Path:
    """从 Script 对象导出（自动计算统计信息）。

    Args:
        script: Script 对象。
        output_dir: 输出目录。
        filename: 输出文件名。

    Returns:
        输出文件路径。
    """
    # 计算统计信息
    if hasattr(script, "compute_stats"):
        script.compute_stats()

    return export_yaml(script, output_dir, filename)


def yaml_to_string(data, indent: int = 2) -> str:
    """将数据转换为 YAML 字符串（不写入文件）。

    用于调试、预览、日志输出等场景。

    Args:
        data: 要转换的数据。
        indent: 缩进空格数。

    Returns:
        YAML 格式字符串。
    """
    if hasattr(data, "model_dump"):
        yaml_data = data.model_dump(mode="json", exclude_none=True)
    elif isinstance(data, dict):
        yaml_data = data
    else:
        yaml_data = data

    return yaml.dump(
        yaml_data,
        Dumper=LRMDumper,
        allow_unicode=True,
        default_flow_style=False,
        sort_keys=False,
        width=120,
        indent=indent,
    )


def validate_yaml_file(file_path: Path) -> tuple[bool, str]:
    """校验 YAML 文件格式是否合法。

    Args:
        file_path: YAML 文件路径。

    Returns:
        (是否合法, 错误信息或文件内容)。
    """
    try:
        content = file_path.read_text(encoding="utf-8")
        # 去除注释行
        lines = [l for l in content.split("\n") if not l.strip().startswith("#")]
        data = yaml.safe_load("\n".join(lines))
        return True, str(data)
    except yaml.YAMLError as e:
        return False, f"YAML 解析错误: {e}"
    except Exception as e:
        return False, f"读取错误: {e}"
